# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HeatingClient' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HeatingClient

  pod 'RxSwift','~> 4.0' 
  pod 'RxCocoa','~> 4.0'
  pod 'Charts'
  
  target 'HeatingClientTests' do
      pod 'RxTest'
      pod 'RxBlocking'
  end
end
