# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HeatingClient' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for HeatingClient

  pod 'RxSwift',:modular_headers => true
  pod 'RxCocoa',:modular_headers => true
  pod 'Charts',:modular_headers => true
  #pod 'Reachability'
  
  target 'HeatingClientTests' do
      pod 'RxTest'
      pod 'RxBlocking'
  end
end
